export const MONGO_URI = process.env.MONGO_URI!;
export const FORM_RESUME_EXPIRES_AT_IN_MILSEC = process.env.FORM_RESUME_EXPIRES_AT_IN_MILSEC!;
export const HASH_SECRET = process.env.HASH_SECRET!;
export const ENC_KEY = process.env.ENC_KEY!;
export const AWS_BUCKET_NAME = process.env.AWS_BUCKET_NAME!;
export const AWS_REGION = process.env.AWS_REGION!;
export const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID!;
export const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY!;
export const CRON_SECRET = process.env.CRON_SECRET!;
export const COOKIE_NAME = process.env.COOKIE_NAME!;
export const NEXTAUTH_SECRET = process.env.NEXTAUTH_SECRET!;
export const NEXT_PUBLIC_PORTAL_BASE_URL = process.env.NEXT_PUBLIC_PORTAL_BASE_URL!;
export const isProd = process.env.NODE_ENV === "production";
export const PORT = process.env.PORT! ?? 3000;
